version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - "mkdir docs/old_tutorials/samples/output"

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

python:
   install:
   - requirements: docs/requirements.txt
#   - method: pip
#     path: .

# formats:
#   - pdf
#   - epub
